etcd:
  endpoints:
    - 10.150.30.21:2379
    - 10.150.30.22:2379
    - 10.150.30.19:2379
  baseKeyToWrite: /nate/CalcBandwidth
  timeout:        5
  certpath:       E:\Documents\_Nate\Computer Related\Private keys\Etcd Certs